// --- DNK-MRH-HEADER ---
// mrh_id: "apps/web/src/canvas/swarm/swarmPropagation.ts"
// purpose: "Swarm Multi-Node Reactive Propagation Engine: Automatically propagates state changes and AI Co-Pilot outputs from Strategy nodes to Design, Code, and Kanban sprint tasks."
// canonical_source: true
// alters_files: []
// triggers_tasks: ["TaskDNA-PHASE-3-SWARM-PROPAGATION"]
// status: "Active"
// version: "1.0.0"
// updated_at: "2026-09-02"
// author: "DNK-e.com Maksym & Gerych"
// license: "DNK-INTERNAL"
// --- END DNK-MRH-HEADER ---

import { Node, Edge } from '@xyflow/react';
import { BrandDNA } from '../../../store/sconesStore';

export interface PropagationResult {
  nodes: Node[];
  propagatedCount: number;
}

export class SwarmPropagationEngine {
  /**
   * Propagate changes from a source node across connected edges to downstream nodes
   */
  public static propagate(
    sourceNodeId: string,
    sourcePayload: Record<string, any>,
    nodes: Node[],
    edges: Edge[],
    brand: BrandDNA
  ): PropagationResult {
    // Find all outgoing edges from sourceNodeId
    const downstreamEdges = edges.filter((e) => e.source === sourceNodeId);
    if (downstreamEdges.length === 0) {
      return { nodes, propagatedCount: 0 };
    }

    const targetIds = new Set(downstreamEdges.map((e) => e.target));
    let propagatedCount = 0;

    const updatedNodes = nodes.map((node) => {
      if (targetIds.has(node.id)) {
        propagatedCount++;
        const currentData = node.data || {};

        // Apply swarm propagation rules based on node type
        if (node.type === 'DesignGalleryNode') {
          return {
            ...node,
            data: {
              ...currentData,
              colors: brand.colors,
              aiParams: brand.aiParams,
              upstreamStrategy: sourcePayload,
              badge: 'Synced via Swarm ⚡',
            },
          };
        }

        if (node.type === 'ApiDocsCodeNode') {
          return {
            ...node,
            data: {
              ...currentData,
              code: `// Auto-generated by Swarm from Strategy: ${brand.brandName}\nconst config = {\n  primaryColor: '${brand.colors.primary}',\n  tone: '${brand.toneOfVoice}',\n  payload: ${JSON.stringify(sourcePayload, null, 2)}\n};`,
            },
          };
        }

        if (node.type === 'SprintKanbanNode') {
          return {
            ...node,
            data: {
              ...currentData,
              title: `${brand.brandName} - Swarm Sprint`,
              injectedTask: {
                id: `swarm-task-${Date.now()}`,
                title: `Execute strategy goal: ${sourcePayload.goal || 'Launch Campaign'}`,
                date: 'Active',
                userAvatar: 'AI',
                userColor: 'bg-indigo-500',
              },
            },
          };
        }

        // Generic upstream propagation update
        return {
          ...node,
          data: {
            ...currentData,
            upstreamPayload: sourcePayload,
          },
        };
      }
      return node;
    });

    return {
      nodes: updatedNodes,
      propagatedCount,
    };
  }
}
