# --- DNK-MRH-HEADER ---
# mrh_id: "deployments/k8s/hpa.yaml"
# purpose: "Kubernetes Horizontal Pod Autoscaler (HPA) for API and Web workloads based on CPU and Memory targets"
# author: "DNK-e.com Maksym"
# license: "MIT"
# status: "Active"
# version: "1.0.0"
# updated_at: "2026-08-29"
# --- END DNK-MRH-HEADER ---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dnk-api-hpa
  namespace: dnk-os
  labels:
    app.kubernetes.io/name: dnk-api-hpa
    app.kubernetes.io/part-of: dnk-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dnk-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dnk-web-hpa
  namespace: dnk-os
  labels:
    app.kubernetes.io/name: dnk-web-hpa
    app.kubernetes.io/part-of: dnk-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dnk-web
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
