# --- DNK-MRH-HEADER ---
# mrh_id: "skills/models.py"
# purpose: "Define models and schemas for the Design Skill Registry."
# canonical_source: true
# status: "Active"
# version: "1.0.0"
# updated_at: "2026-08-11"
# author: "DNK-e.com Maksym"
# license: "DNK-INTERNAL"
# --- END DNK-MRH-HEADER ---

from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class SkillContract(BaseModel):
    id: str = Field(..., description="Unique skill identifier, e.g. dnk.ui.generate_workspace")
    version: str = Field("1.0.0", description="Semantic version of the skill")
    risk_level: str = Field("L1", description="Policy risk level: L0, L1, L2, L3, L4")
    input_schema: List[str] = Field(default_factory=list, description="List of required input parameters")
    output_artifacts: List[str] = Field(default_factory=list, description="Types of artifacts generated by this skill")
    approval_required: bool = Field(False, description="Whether explicit approval is required before execution")

class BaseSkill:
    contract: SkillContract

    def execute(self, context: Dict[str, Any]) -> Dict[str, Any]:
        raise NotImplementedError("Skills must implement execute() method.")
