apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ include \"dnk-os.fullname\" . }}-api-hpa"
  labels:
    app.kubernetes.io/name: "{{ include \"dnk-os.name\" . }}-api"
    app.kubernetes.io/part-of: dnk-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ include \"dnk-os.fullname\" . }}-api"
  minReplicas: {{ .Values.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.api.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.autoscaling.targetMemoryUtilizationPercentage }}
